[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
orao_solana_vrf_callback = "3s1QVFx1cZ5W7ubDfvz9d8XNSz8kfNQp69Tc1mjr6wrs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/mlem-mlem/orao-solana-vrf-callback/keypairs/deployer-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
